services: 
  coraje-backend:
    build: .
    image: coraje:latest
    container_name: coraje-backend
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env