name: Update .env on VPS

on:
  workflow_dispatch:
    inputs:
      env_vars:
        description: 'Variables in JSON format (e.g. {"PORT": "3000"})'
        required: true
        default: '{}'

jobs:
  update-env:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Update Env Vars
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/projects/coraje-server
            echo '${{ github.event.inputs.env_vars }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > .env
